
spring:
  application:
    name: server
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: dev-ulixqg71ihyco2h1.us.auth0.com
          audiences: http://localhost:8080/api/v1

server:
  servlet:
    context-path: /api/v1
  port: ${SERVER_DEV_PORT:8080}
