---
id: 8755b07f-6da0-4132-bf73-8f771cd44519
---
sequenceDiagram
  actor user as Bob
  participant ui as UI
  participant auth0 as Auth0
  participant server as Server
  participant db as Database

  autonumber
  user ->> ui : Visit website
  ui ->> user: Display landing page
  user ->> ui : Click Home button
  ui ->> auth0 : Auth0 sign-in redirect
  auth0 ->> ui : response(JWT)
  ui ->> user : display Home page
  ui ->> server: sendUserDataToServer(Header: JWT)
  ui ->> server: getUserLibrary(Header: JWT)
  server ->> auth0 : authUser(JWT)
  auth0 ->> server : User Data
  server ->> db: getAllUserBooks(auth0Id)
  db ->> server: List<UserBooks>
  server->> home : { userbooks (json)}
  ui ->>user: Render all user books